### ISSUE TITLE
ExaminfoController.java  AnswerinfoMapper.java QuestioninfoMapper.java your filename should be fllowed Upper Camel Case

### ISSUE THREAD

**Issue by luhc228** [PPQiu/oes-backend#3]
https://github.com/PPQiu/OES/blob/e05799008719a903dcc753d4d0ed222ae0591900/oes/src/main/java/cn/aitechlab/oes/controller/ExaminfoController.java#L1

**Comment by PPQiu** [comment]
这个意思是我要把类似于Examinfo的改成ExamInfo?

**Comment by luhc228** [comment]
> 这个意思是我要把类似于Examinfo的改成ExamInfo?有类似问题的都改？

是的。

**Comment by PPQiu** [comment]
好，下次上传一定改，刚传的那个忘改了，我完善了登录接口，我觉得可以用了

**Comment by PPQiu** [comment]
已改
